# Article constants

ARTICLE_TITLE_MIN_LENGTH = 10
ARTICLE_TITLE_MAX_LENGTH = 150


# Users

USERNAME_MIN_LENGTH = 1
USERNAME_MAX_LENGTH = 50

PASSWORD_MIN_LENGTH = 6
PASSWORD_MAX_LENGTH = 14
HASHPASSWORD_MAX_LENGTH = 255
