# Generated by Django 4.1.4 on 2022-12-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_remove_transaction_balance_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-user', '-balance'], 'verbose_name': ('Account',), 'verbose_name_plural': 'Accounts'},
        ),
    ]
