# Generated by Django 4.1.4 on 2022-12-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Account name'),
        ),
        migrations.RemoveField(
            model_name='account',
            name='transaction',
        ),
        migrations.AddField(
            model_name='account',
            name='transaction',
            field=models.ManyToManyField(to='finances.transaction'),
        ),
    ]
