# Generated by Django 4.1.4 on 2022-12-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_alter_account_options_remove_account_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remaining balance'),
        ),
    ]
