# Generated by Django 4.1.4 on 2022-12-23 08:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, max_length=10, populate_from='description', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=15, populate_from='description', unique=True),
        ),
    ]
