# Generated by Django 4.1.4 on 2022-12-23 14:26

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Remaining balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=10, populate_from='name', unique=True),
        ),
    ]
