# Generated by Django 4.1.4 on 2022-12-24 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 24, 12, 37, 11, 183901), verbose_name='Date'),
        ),
    ]
