# Generated by Django 4.1.4 on 2023-01-10 08:00

from django.db import migrations, models
import django.db.models.deletion
import finances.models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0018_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(default=finances.models.Category.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='finances.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Description'),
        ),
    ]
