"""articles init

Revision ID: cf7c4eb0a1d2
Revises: c95c7f6a9b9e
Create Date: 2023-01-17 16:46:59.812097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7c4eb0a1d2'
down_revision = 'c95c7f6a9b9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
