"""articles article owner added

Revision ID: eebf40845f31
Revises: 342360db8150
Create Date: 2023-01-19 11:34:24.987819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "eebf40845f31"
down_revision = "342360db8150"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles", sa.Column("user", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.drop_constraint("articles_owner_fkey", "articles", type_="foreignkey")
    op.create_foreign_key(
        None, "articles", "users", ["user"], ["uuid"], ondelete="SET NULL"
    )
    op.drop_column("articles", "owner")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles",
        sa.Column("owner", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "articles", type_="foreignkey")
    op.create_foreign_key(
        "articles_owner_fkey",
        "articles",
        "users",
        ["owner"],
        ["uuid"],
        ondelete="SET NULL",
    )
    op.drop_column("articles", "user")
    # ### end Alembic commands ###
