"""users init

Revision ID: f3168759f1d3
Revises: cf7c4eb0a1d2
Create Date: 2023-01-18 17:10:39.646944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f3168759f1d3"
down_revision = "cf7c4eb0a1d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
