"""Phone number field and Email address field have been changed to value

Revision ID: 2e66ee285716
Revises: f6b4ce45bae3
Create Date: 2022-12-06 20:12:23.190934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e66ee285716'
down_revision = 'f6b4ce45bae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.String(length=50), nullable=True))
        batch_op.drop_index('ix_emails_address')
        batch_op.create_index(batch_op.f('ix_emails_value'), ['value'], unique=False)
        batch_op.drop_column('address')

    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.String(length=50), nullable=True))
        batch_op.drop_index('ix_phones_number')
        batch_op.create_index(batch_op.f('ix_phones_value'), ['value'], unique=False)
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('ix_phones_value'))
        batch_op.create_index('ix_phones_number', ['number'], unique=False)
        batch_op.drop_column('value')

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('ix_emails_value'))
        batch_op.create_index('ix_emails_address', ['address'], unique=False)
        batch_op.drop_column('value')

    # ### end Alembic commands ###
