"""edited_at now nullable

Revision ID: 7ad3b53f6b59
Revises: a4855f7b217b
Create Date: 2022-12-09 11:02:14.350496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ad3b53f6b59'
down_revision = 'a4855f7b217b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('edited_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('edited_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
