"""foreign key behavior

Revision ID: a4855f7b217b
Revises: 2e66ee285716
Create Date: 2022-12-08 09:02:09.477555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4855f7b217b'
down_revision = '2e66ee285716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_constraint('emails_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'records', ['record_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint('notes_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'note_books', ['book_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.drop_constraint('phones_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'records', ['record_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('record_books', schema=None) as batch_op:
        batch_op.drop_constraint('record_books_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['username_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint('records_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'record_books', ['book_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('records_ibfk_1', 'record_books', ['book_id'], ['id'])

    with op.batch_alter_table('record_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('record_books_ibfk_1', 'users', ['username_id'], ['id'])

    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('phones_ibfk_1', 'records', ['record_id'], ['id'])

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notes_ibfk_1', 'note_books', ['book_id'], ['id'])

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('emails_ibfk_1', 'records', ['record_id'], ['id'])

    # ### end Alembic commands ###
