"""name - tag_name

Revision ID: dfe94ecd2c3d
Revises: 7ad3b53f6b59
Create Date: 2022-12-09 11:49:09.578185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfe94ecd2c3d'
down_revision = '7ad3b53f6b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_name', sa.String(length=30), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=30), nullable=False))
        batch_op.drop_column('tag_name')

    # ### end Alembic commands ###
