"""book title no more unique

Revision ID: f6b4ce45bae3
Revises: 
Create Date: 2022-12-06 18:04:08.299838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b4ce45bae3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_books', schema=None) as batch_op:
        batch_op.drop_index('ix_note_books_title')
        batch_op.create_index(batch_op.f('ix_note_books_title'), ['title'], unique=False)

    with op.batch_alter_table('record_books', schema=None) as batch_op:
        batch_op.drop_index('ix_record_books_title')
        batch_op.create_index(batch_op.f('ix_record_books_title'), ['title'], unique=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    with op.batch_alter_table('record_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_record_books_title'))
        batch_op.create_index('ix_record_books_title', ['title'], unique=False)

    with op.batch_alter_table('note_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_books_title'))
        batch_op.create_index('ix_note_books_title', ['title'], unique=False)

    # ### end Alembic commands ###
