# Models

# Category
CATEGORY_MIN_LEGNTH = 3
CATEGORY_MAX_LEGNTH = 50
CATEGORY_MAX_URL = 30

# Transaction
DESCRIPTION_MIN_LENGTH = 3
DESCRIPTION_MAX_LENGTH = 100
DECIMAL_MAX_DIGITS = 10  # for 1_000_000_000.XXXXXX -> 10 symbols before dot. Up to 9 billion
DECIMAL_PLACES = 2  # 10_000_000.XX -> 2 symbols after dot
DESCRIPTION_MAX_URL = 15

# Account
ACCOUNT_MIN_LENGTH = 3
ACCOUNT_MAX_LENGTH = 50
ACCOUNT_MAX_URL = 10
