"""monobank storage

Revision ID: 313cb0ea2ff9
Revises: 594d3eff20a6
Create Date: 2022-12-20 16:27:10.953905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313cb0ea2ff9'
down_revision = '594d3eff20a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monobank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=60), nullable=True),
    sa.Column('rate_sell', sa.Integer(), nullable=True),
    sa.Column('rate_buy', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monobank')
    # ### end Alembic commands ###
