"""init

Revision ID: 594d3eff20a6
Revises: 
Create Date: 2022-12-19 11:31:51.759442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594d3eff20a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=70), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('minor', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currencies')
    # ### end Alembic commands ###
