"""monobank rates to float

Revision ID: af5d4b285746
Revises: e72360df3fd6
Create Date: 2022-12-20 18:13:14.737076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5d4b285746'
down_revision = 'e72360df3fd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monobank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=60), nullable=True),
    sa.Column('rate_sell', sa.Float(), nullable=True),
    sa.Column('rate_buy', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monobank')
    # ### end Alembic commands ###
