"""monobank rates to float

Revision ID: e72360df3fd6
Revises: 313cb0ea2ff9
Create Date: 2022-12-20 18:11:47.066644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72360df3fd6'
down_revision = '313cb0ea2ff9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
